name: "Deploy Apex Tournament Manager"

on:
  push:
    branches:
      - "release"

env:
  PROJECT_PATH: ApexTournamentManager.sln

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Setup MSbuild
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          msbuild-architecture: x64

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0

      - name: Restore NuGet packages
        run: nuget restore ${{ env.PROJECT_PATH }}
  
      - name: Build Solution
        run: msbuild build ${{ env.PROJECT_PATH }} -c Release --no-restore
  
      - run: msbuild publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile --no-build